version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily

- package-ecosystem: terraform
  directories:
  - /modules/cache-policy
  - /modules/distribution
  - /modules/origin-access-control
  - /modules/origin-request-policy
  - /modules/response-headers-policy
  schedule:
    interval: weekly
